#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VeterinariadeBolsillo.Resource", IsApplication=true)]

namespace VeterinariadeBolsillo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int my_lightyellow = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int my_yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ajustes = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Alta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Baner1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Buscar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Camera = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Clock = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Fondo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Fondo2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Fondo3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int glass = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_more_vert_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icono = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int list = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int LogoChico = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ProximasVisitas = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int MyButton = 2131230726;
			
			// aapt resource value: 0x7f08003d
			public const int agregarMascota = 2131230781;
			
			// aapt resource value: 0x7f080005
			public const int baseLinear = 2131230725;
			
			// aapt resource value: 0x7f080011
			public const int btAgregarMascota = 2131230737;
			
			// aapt resource value: 0x7f08001f
			public const int btAjustes = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int btAlta = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int btBuscar = 2131230745;
			
			// aapt resource value: 0x7f080033
			public const int btCamera = 2131230771;
			
			// aapt resource value: 0x7f080025
			public const int btCancelar = 2131230757;
			
			// aapt resource value: 0x7f08000f
			public const int btEditarAnimal = 2131230735;
			
			// aapt resource value: 0x7f080026
			public const int btGuardar = 2131230758;
			
			// aapt resource value: 0x7f08000c
			public const int btIndicaciones = 2131230732;
			
			// aapt resource value: 0x7f080004
			public const int btLogin = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int btMisMascotas = 2131230731;
			
			// aapt resource value: 0x7f08002f
			public const int btProgramarVisita = 2131230767;
			
			// aapt resource value: 0x7f08000e
			public const int btProximasVisitas = 2131230734;
			
			// aapt resource value: 0x7f08001e
			public const int btVisitas = 2131230750;
			
			// aapt resource value: 0x7f08003a
			public const int calAccountName = 2131230778;
			
			// aapt resource value: 0x7f080039
			public const int calDisplayName = 2131230777;
			
			// aapt resource value: 0x7f080035
			public const int calendar = 2131230773;
			
			// aapt resource value: 0x7f080001
			public const int imageView1 = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int img = 2131230739;
			
			// aapt resource value: 0x7f080029
			public const int imgMascota = 2131230761;
			
			// aapt resource value: 0x7f080010
			public const int imgVeterinaria = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout1 = 2131230740;
			
			// aapt resource value: 0x7f08001c
			public const int linearLayout2 = 2131230748;
			
			// aapt resource value: 0x7f080028
			public const int linearLayout3 = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int linearLayout4 = 2131230762;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout5 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout6 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout7 = 2131230733;
			
			// aapt resource value: 0x7f08001a
			public const int lstAnimales = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int lstMacotas = 2131230738;
			
			// aapt resource value: 0x7f080037
			public const int lstProximasVisitas = 2131230775;
			
			// aapt resource value: 0x7f080036
			public const int lstVisitas = 2131230774;
			
			// aapt resource value: 0x7f08003b
			public const int mainMenu = 2131230779;
			
			// aapt resource value: 0x7f08003f
			public const int misIndicaciones = 2131230783;
			
			// aapt resource value: 0x7f08003e
			public const int misTurnos = 2131230782;
			
			// aapt resource value: 0x7f08003c
			public const int overflow = 2131230780;
			
			// aapt resource value: 0x7f080032
			public const int space1 = 2131230770;
			
			// aapt resource value: 0x7f080030
			public const int spnSexo = 2131230768;
			
			// aapt resource value: 0x7f080000
			public const int textView1 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int toolbar1 = 2131230727;
			
			// aapt resource value: 0x7f080038
			public const int txActividad = 2131230776;
			
			// aapt resource value: 0x7f08001b
			public const int txCaracteristicas = 2131230747;
			
			// aapt resource value: 0x7f08002e
			public const int txComentariosInternos = 2131230766;
			
			// aapt resource value: 0x7f080024
			public const int txDescripcion = 2131230756;
			
			// aapt resource value: 0x7f080018
			public const int txDni = 2131230744;
			
			// aapt resource value: 0x7f080031
			public const int txDocDueño = 2131230769;
			
			// aapt resource value: 0x7f080023
			public const int txDuracion = 2131230755;
			
			// aapt resource value: 0x7f08002b
			public const int txEspecie = 2131230763;
			
			// aapt resource value: 0x7f080020
			public const int txFechaInicio = 2131230752;
			
			// aapt resource value: 0x7f08002c
			public const int txFechaNacimiento = 2131230764;
			
			// aapt resource value: 0x7f080034
			public const int txFechaVisita = 2131230772;
			
			// aapt resource value: 0x7f080022
			public const int txFrecuencia = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int txHoraInicio = 2131230753;
			
			// aapt resource value: 0x7f080027
			public const int txMascota = 2131230759;
			
			// aapt resource value: 0x7f080015
			public const int txNombre = 2131230741;
			
			// aapt resource value: 0x7f080003
			public const int txPassword = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int txPersona = 2131230728;
			
			// aapt resource value: 0x7f080016
			public const int txRaza = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int txUsuario = 2131230722;
			
			// aapt resource value: 0x7f080017
			public const int txVeterinaria = 2131230743;
			
			// aapt resource value: 0x7f08002d
			public const int txVisita = 2131230765;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginUsuario = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pHome = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pHome2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int pRowMascota = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int vAgregarMascota = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int vAnimalView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int vBuscarAnimal = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int vHome = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int vIndicacion = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int vMascota = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int vNuevoAnimal = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int vProgramarVisita = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int vProximasVisitas = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int vProximasVisitasAnimal = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int vVisitaView = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
