//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VeterinariadeBolsillo.MiVetService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiVetServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MiVetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogInOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertVisitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertVeterinariaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertMascotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVisitasDeLaVeterinariaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAnimalesDeLaVeterinariaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiVetService() {
            this.Url = "http://fabricio-001-site1.mywindowshosting.com/MiVetService/MiVetService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event LogInCompletedEventHandler LogInCompleted;
        
        /// <remarks/>
        public event UpsertVisitaCompletedEventHandler UpsertVisitaCompleted;
        
        /// <remarks/>
        public event UpsertVeterinariaCompletedEventHandler UpsertVeterinariaCompleted;
        
        /// <remarks/>
        public event UpsertPersonaCompletedEventHandler UpsertPersonaCompleted;
        
        /// <remarks/>
        public event UpsertMascotaCompletedEventHandler UpsertMascotaCompleted;
        
        /// <remarks/>
        public event UpsertAnimalCompletedEventHandler UpsertAnimalCompleted;
        
        /// <remarks/>
        public event GetVisitasDeLaVeterinariaCompletedEventHandler GetVisitasDeLaVeterinariaCompleted;
        
        /// <remarks/>
        public event GetAnimalesDeLaVeterinariaCompletedEventHandler GetAnimalesDeLaVeterinariaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test(Animal a, Mascota m, Persona p, Veterinaria v, Visita vis) {
            this.Invoke("Test", new object[] {
                        a,
                        m,
                        p,
                        v,
                        vis});
        }
        
        /// <remarks/>
        public void TestAsync(Animal a, Mascota m, Persona p, Veterinaria v, Visita vis) {
            this.TestAsync(a, m, p, v, vis, null);
        }
        
        /// <remarks/>
        public void TestAsync(Animal a, Mascota m, Persona p, Veterinaria v, Visita vis, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        a,
                        m,
                        p,
                        v,
                        vis}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object LogIn(string usuario, string contraseña) {
            object[] results = this.Invoke("LogIn", new object[] {
                        usuario,
                        contraseña});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void LogInAsync(string usuario, string contraseña) {
            this.LogInAsync(usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void LogInAsync(string usuario, string contraseña, object userState) {
            if ((this.LogInOperationCompleted == null)) {
                this.LogInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogInOperationCompleted);
            }
            this.InvokeAsync("LogIn", new object[] {
                        usuario,
                        contraseña}, this.LogInOperationCompleted, userState);
        }
        
        private void OnLogInOperationCompleted(object arg) {
            if ((this.LogInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogInCompleted(this, new LogInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpsertVisita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Visita UpsertVisita(Visita visita) {
            object[] results = this.Invoke("UpsertVisita", new object[] {
                        visita});
            return ((Visita)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertVisitaAsync(Visita visita) {
            this.UpsertVisitaAsync(visita, null);
        }
        
        /// <remarks/>
        public void UpsertVisitaAsync(Visita visita, object userState) {
            if ((this.UpsertVisitaOperationCompleted == null)) {
                this.UpsertVisitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertVisitaOperationCompleted);
            }
            this.InvokeAsync("UpsertVisita", new object[] {
                        visita}, this.UpsertVisitaOperationCompleted, userState);
        }
        
        private void OnUpsertVisitaOperationCompleted(object arg) {
            if ((this.UpsertVisitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertVisitaCompleted(this, new UpsertVisitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpsertVeterinaria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Veterinaria UpsertVeterinaria(Veterinaria veterinaria) {
            object[] results = this.Invoke("UpsertVeterinaria", new object[] {
                        veterinaria});
            return ((Veterinaria)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertVeterinariaAsync(Veterinaria veterinaria) {
            this.UpsertVeterinariaAsync(veterinaria, null);
        }
        
        /// <remarks/>
        public void UpsertVeterinariaAsync(Veterinaria veterinaria, object userState) {
            if ((this.UpsertVeterinariaOperationCompleted == null)) {
                this.UpsertVeterinariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertVeterinariaOperationCompleted);
            }
            this.InvokeAsync("UpsertVeterinaria", new object[] {
                        veterinaria}, this.UpsertVeterinariaOperationCompleted, userState);
        }
        
        private void OnUpsertVeterinariaOperationCompleted(object arg) {
            if ((this.UpsertVeterinariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertVeterinariaCompleted(this, new UpsertVeterinariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpsertPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Persona UpsertPersona(Persona persona) {
            object[] results = this.Invoke("UpsertPersona", new object[] {
                        persona});
            return ((Persona)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertPersonaAsync(Persona persona) {
            this.UpsertPersonaAsync(persona, null);
        }
        
        /// <remarks/>
        public void UpsertPersonaAsync(Persona persona, object userState) {
            if ((this.UpsertPersonaOperationCompleted == null)) {
                this.UpsertPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertPersonaOperationCompleted);
            }
            this.InvokeAsync("UpsertPersona", new object[] {
                        persona}, this.UpsertPersonaOperationCompleted, userState);
        }
        
        private void OnUpsertPersonaOperationCompleted(object arg) {
            if ((this.UpsertPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertPersonaCompleted(this, new UpsertPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpsertMascota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Mascota UpsertMascota(Mascota mascota) {
            object[] results = this.Invoke("UpsertMascota", new object[] {
                        mascota});
            return ((Mascota)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertMascotaAsync(Mascota mascota) {
            this.UpsertMascotaAsync(mascota, null);
        }
        
        /// <remarks/>
        public void UpsertMascotaAsync(Mascota mascota, object userState) {
            if ((this.UpsertMascotaOperationCompleted == null)) {
                this.UpsertMascotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertMascotaOperationCompleted);
            }
            this.InvokeAsync("UpsertMascota", new object[] {
                        mascota}, this.UpsertMascotaOperationCompleted, userState);
        }
        
        private void OnUpsertMascotaOperationCompleted(object arg) {
            if ((this.UpsertMascotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertMascotaCompleted(this, new UpsertMascotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpsertAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal UpsertAnimal(Animal animal) {
            object[] results = this.Invoke("UpsertAnimal", new object[] {
                        animal});
            return ((Animal)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertAnimalAsync(Animal animal) {
            this.UpsertAnimalAsync(animal, null);
        }
        
        /// <remarks/>
        public void UpsertAnimalAsync(Animal animal, object userState) {
            if ((this.UpsertAnimalOperationCompleted == null)) {
                this.UpsertAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertAnimalOperationCompleted);
            }
            this.InvokeAsync("UpsertAnimal", new object[] {
                        animal}, this.UpsertAnimalOperationCompleted, userState);
        }
        
        private void OnUpsertAnimalOperationCompleted(object arg) {
            if ((this.UpsertAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertAnimalCompleted(this, new UpsertAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVisitasDeLaVeterinaria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Visita[] GetVisitasDeLaVeterinaria(int vetId) {
            object[] results = this.Invoke("GetVisitasDeLaVeterinaria", new object[] {
                        vetId});
            return ((Visita[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVisitasDeLaVeterinariaAsync(int vetId) {
            this.GetVisitasDeLaVeterinariaAsync(vetId, null);
        }
        
        /// <remarks/>
        public void GetVisitasDeLaVeterinariaAsync(int vetId, object userState) {
            if ((this.GetVisitasDeLaVeterinariaOperationCompleted == null)) {
                this.GetVisitasDeLaVeterinariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVisitasDeLaVeterinariaOperationCompleted);
            }
            this.InvokeAsync("GetVisitasDeLaVeterinaria", new object[] {
                        vetId}, this.GetVisitasDeLaVeterinariaOperationCompleted, userState);
        }
        
        private void OnGetVisitasDeLaVeterinariaOperationCompleted(object arg) {
            if ((this.GetVisitasDeLaVeterinariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVisitasDeLaVeterinariaCompleted(this, new GetVisitasDeLaVeterinariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAnimalesDeLaVeterinaria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Animal[] GetAnimalesDeLaVeterinaria(int vetId) {
            object[] results = this.Invoke("GetAnimalesDeLaVeterinaria", new object[] {
                        vetId});
            return ((Animal[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAnimalesDeLaVeterinariaAsync(int vetId) {
            this.GetAnimalesDeLaVeterinariaAsync(vetId, null);
        }
        
        /// <remarks/>
        public void GetAnimalesDeLaVeterinariaAsync(int vetId, object userState) {
            if ((this.GetAnimalesDeLaVeterinariaOperationCompleted == null)) {
                this.GetAnimalesDeLaVeterinariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAnimalesDeLaVeterinariaOperationCompleted);
            }
            this.InvokeAsync("GetAnimalesDeLaVeterinaria", new object[] {
                        vetId}, this.GetAnimalesDeLaVeterinariaOperationCompleted, userState);
        }
        
        private void OnGetAnimalesDeLaVeterinariaOperationCompleted(object arg) {
            if ((this.GetAnimalesDeLaVeterinariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAnimalesDeLaVeterinariaCompleted(this, new GetAnimalesDeLaVeterinariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Animal {
        
        private int idField;
        
        private string documentoField;
        
        private string nombreField;
        
        private string especieField;
        
        private string sexoField;
        
        private System.DateTime fechaNacimientoField;
        
        private byte[] fotoField;
        
        private int idVeterinariaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public int IdVeterinaria {
            get {
                return this.idVeterinariaField;
            }
            set {
                this.idVeterinariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Visita {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private int idAnimalField;
        
        private int idVeterinariaField;
        
        private string actividadField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int IdAnimal {
            get {
                return this.idAnimalField;
            }
            set {
                this.idAnimalField = value;
            }
        }
        
        /// <remarks/>
        public int IdVeterinaria {
            get {
                return this.idVeterinariaField;
            }
            set {
                this.idVeterinariaField = value;
            }
        }
        
        /// <remarks/>
        public string Actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Veterinaria {
        
        private int idField;
        
        private string nombreField;
        
        private string ubicacionField;
        
        private bool urgenciasField;
        
        private decimal latitudField;
        
        private decimal longitudField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Urgencias {
            get {
                return this.urgenciasField;
            }
            set {
                this.urgenciasField = value;
            }
        }
        
        /// <remarks/>
        public decimal Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public decimal Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona {
        
        private int idField;
        
        private string nombreField;
        
        private string documentoField;
        
        private string telefonoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mascota {
        
        private int idField;
        
        private int idAnimalField;
        
        private int idPersonaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdAnimal {
            get {
                return this.idAnimalField;
            }
            set {
                this.idAnimalField = value;
            }
        }
        
        /// <remarks/>
        public int IdPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LogInCompletedEventHandler(object sender, LogInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpsertVisitaCompletedEventHandler(object sender, UpsertVisitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertVisitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertVisitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Visita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Visita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpsertVeterinariaCompletedEventHandler(object sender, UpsertVeterinariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertVeterinariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertVeterinariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Veterinaria Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Veterinaria)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpsertPersonaCompletedEventHandler(object sender, UpsertPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Persona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Persona)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpsertMascotaCompletedEventHandler(object sender, UpsertMascotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertMascotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertMascotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Mascota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Mascota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpsertAnimalCompletedEventHandler(object sender, UpsertAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetVisitasDeLaVeterinariaCompletedEventHandler(object sender, GetVisitasDeLaVeterinariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVisitasDeLaVeterinariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVisitasDeLaVeterinariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Visita[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Visita[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAnimalesDeLaVeterinariaCompletedEventHandler(object sender, GetAnimalesDeLaVeterinariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAnimalesDeLaVeterinariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAnimalesDeLaVeterinariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591