#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VeterinariadeBolsillo.Resource", IsApplication=true)]

namespace VeterinariadeBolsillo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int my_lightyellow = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int my_yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ajustes = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Alta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Baner1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Buscar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Fondo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LogoChico = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProximasVisitas = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int MyButton = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int baseLinear = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int btAjustes = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int btAlta = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int btBuscar = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int btCancelar = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int btGuardar = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int btLogin = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int btVisitas = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int imgVeterinaria = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int spnSexo = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int txDocDueño = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int txEspecie = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int txFechaNacimiento = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int txNombre = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int txPassword = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int txRaza = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int txUsuario = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int txVeterinaria = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginUsuario = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pHome = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int vHome = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int vNuevoAnimal = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
